version: '3.3'

services:
  # ---------------------------
  # Team Three
  # ---------------------------
  team-three:
    container_name: "team-three"
    hostname: "team-three"
    build: .
    image: team-three
    ports:
      - 8080:8080